# Generated by Django 5.2.5 on 2025-09-06 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careerbookmark',
            options={'verbose_name': 'Career Bookmark', 'verbose_name_plural': 'Career Bookmarks'},
        ),
    ]
