# Generated by Django 5.2.5 on 2025-08-16 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_iq', models.CharField(choices=[('LOW', 'Low'), ('AVERAGE', 'Average'), ('HIGH', 'High')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='careers.career')),
                ('interests', models.ManyToManyField(blank=True, to='careers.interest')),
            ],
        ),
    ]
